modLoader="javafml"
loaderVersion="[47,)"
license="MIT-CODE, ARR-ART"

[[mods]]
modId="create_bnz"
version="${file.jarVersion}"
displayName="Create: Block n' Zapping"
logoFile="pack.png"
authors="LopyLuna"
description='''
An addon that Adds back Block Zapper from Old Create Versions & Reimagines it!
'''

[[dependencies.create_bnz]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_bnz]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_bnz]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.f,)"
    ordering="AFTER"
    side="BOTH"